"""Ports used by use cases (dependency inversion boundary)."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import datetime
from typing import Any, Protocol


class Repository(Protocol):
    def list_all(self) -> list[dict[str, Any]]: ...
    def find_by_id(self, record_id: str) -> dict[str, Any] | None: ...
    def add(self, data: Mapping[str, Any]) -> dict[str, Any]: ...
    def update(self, data: Mapping[str, Any]) -> dict[str, Any]: ...
    def delete(self, ids: Sequence[str]) -> bool: ...
    def replace_all(self, records: Sequence[Mapping[str, Any]]) -> None: ...


class GpioController(Protocol):
    def configure(self, valve_pins: Sequence[int]) -> None: ...
    def turn_on(self, pin: int) -> None: ...
    def turn_off(self, pin: int, keep_pump_on: bool = False) -> None: ...
    def close(self) -> None: ...


class Clock(Protocol):
    def now(self) -> datetime: ...
